/*  d3  */  
document.write("<script src='d3.v5.min.js'><\/script>")    
document.write("<script src='d3-force-3d.js'><\/script>")    
document.write("<script src='d3-force-bounce.js'><\/script>")    
document.write("<script src='d3-force-bounce.min.js'><\/script>")    
document.write("<script src='d3-force-magnetic.js'><\/script>")    
document.write("<script src='d3-force-magnetic.min.js'><\/script>")    
document.write("<script src='d3-force-pod.min.js'><\/script>")    
document.write("<script src='d3-force-surface.js'><\/script>")    
document.write("<script src='d3-force-surface.min.js'><\/script>")    
document.write("<script src='d3-geo.js'><\/script>")    
document.write("<script src='d3-geo-polygon.js'><\/script>")    
document.write("<script src='d3-geo-projection-clip-polyhedral.js'><\/script>")    
document.write("<script src='d3-geo-voronoi.js'><\/script>")    
document.write("<script src='d3-inertia.js'><\/script>")    
document.write("<script src='d3-octree.js'><\/script>")    
/*  topojson */  
document.write("<script src='topojson.v3.min.js'><\/script>")    
/*  three */  
document.write("<script src='three.min.js'><\/script>")    
document.write("<script src='three-trackballcontrols.min.js'><\/script>")    
