/* https://www.irt.org/script/974.htm */  
/*  bosons */  
/*  controls */  
document.write("<script src='control-key.js'><\/script>")    
document.write("<script src='control-mouseDown.js'><\/script>")    
document.write("<script src='control-mouseLeave.js'><\/script>")    
document.write("<script src='control-mouseMove.js'><\/script>")    
document.write("<script src='control-mouseUp.js'><\/script>")    
document.write("<script src='control-pos.js'><\/script>")    
document.write("<script src='control-raycaster.js'><\/script>")    
document.write("<script src='control-timer.js'><\/script>")    
document.write("<script src='control-touchEnd.js'><\/script>")    
document.write("<script src='control-touchMove.js'><\/script>")    
document.write("<script src='control-versor.js'><\/script>")    
document.write("<script src='control-wen.js'><\/script>")    
/*  data */  
document.write("<script src='data-worldTopo110m.js'><\/script>")    
/*  forces */  
document.write("<script src='force-bowl.js'><\/script>")    
document.write("<script src='force-box.js'><\/script>")    
document.write("<script src='force-center.js'><\/script>")    
document.write("<script src='force-collide.js'><\/script>")    
document.write("<script src='force-crash.js'><\/script>")    
document.write("<script src='force-crop.js'><\/script>")    
document.write("<script src='force-curb.js'><\/script>")    
document.write("<script src='force-energy.js'><\/script>")    
document.write("<script src='force-link.js'><\/script>")    
document.write("<script src='force-magnetic.js'><\/script>")    
document.write("<script src='force-manybody.js'><\/script>")    
document.write("<script src='force-x.js'><\/script>")    
document.write("<script src='force-y.js'><\/script>")    
document.write("<script src='force-z.js'><\/script>")    
/*  geos projections */  
document.write("<script src='geo-cox.js'><\/script>")    
document.write("<script src='geo-futuri.js'><\/script>")    
document.write("<script src='geo-hedrals.js'><\/script>")    
document.write("<script src='geo-myriad.js'><\/script>")    
document.write("<script src='geo-natform.js'><\/script>")    
document.write("<script src='geo-tetra.js'><\/script>")    
document.write("<script src='geo-unimercator.js'><\/script>")    
document.write("<script src='geo-uniwen.js'><\/script>")    
/*  lib */  
document.write("<script src='lib-complex.js'><\/script>")    
document.write("<script src='lib-dat.gui.js'><\/script>")    
document.write("<script src='lib-papaparse.js'><\/script>")    
/*  muons */  
document.write("<script src='muon-animas.js'><\/script>")    
document.write("<script src='muon-animation.js'><\/script>")    
document.write("<script src='muon-anitem.js'><\/script>")    
document.write("<script src='muon-audio.js'><\/script>")    
document.write("<script src='muon-boform.js'><\/script>")    
document.write("<script src='muon-clone.js'><\/script>")    
document.write("<script src='muon-delaunator.js'><\/script>")    
document.write("<script src='muon-delaunay.js'><\/script>")    
document.write("<script src='muon-fibonat.js'><\/script>")    
document.write("<script src='muon-forces.js'><\/script>")    
document.write("<script src='muon-geoj.js'><\/script>")    
document.write("<script src='muon-geom.js'><\/script>")    
document.write("<script src='muon-geonode.js'><\/script>")    
document.write("<script src='muon-graticule.js'><\/script>")    
document.write("<script src='muon-image.js'><\/script>")    
document.write("<script src='muon-init.js'><\/script>")    
document.write("<script src='muon-kruskal.js'><\/script>")    
document.write("<script src='muon-lacer.js'><\/script>")    
document.write("<script src='muon-liner.js'><\/script>")    
document.write("<script src='muon-mapper.js'><\/script>")    
document.write("<script src='muon-mouse.js'><\/script>")    
document.write("<script src='muon-nat.js'><\/script>")    
document.write("<script src='muon-newton.js'><\/script>")    
document.write("<script src='muon-pacer.js'><\/script>")    
document.write("<script src='muon-polyhedral.js'><\/script>")    
document.write("<script src='muon-profier.js'><\/script>")    
document.write("<script src='muon-proj3ct.js'><\/script>")    
document.write("<script src='muon-props.js'><\/script>")    
document.write("<script src='muon-quad.js'><\/script>")    
document.write("<script src='muon-ric.js'><\/script>")    
document.write("<script src='muon-sim.js'><\/script>")    
document.write("<script src='muon-snap.js'><\/script>")    
document.write("<script src='muon-stace.js'><\/script>")    
document.write("<script src='muon-stats.js'><\/script>")    
document.write("<script src='muon-store.js'><\/script>")    
document.write("<script src='muon-tim.js'><\/script>")    
document.write("<script src='muon-timer.js'><\/script>")    
document.write("<script src='muon-versor.js'><\/script>")    
document.write("<script src='muon-voro.js'><\/script>")    
document.write("<script src='muon-wen.js'><\/script>")    
/*  halo */  
document.write("<script src='halo-core.js'><\/script>")    
document.write("<script src='halo-ent.js'><\/script>")    
document.write("<script src='halo-fuel.js'><\/script>")    
document.write("<script src='halo-img.js'><\/script>")    
document.write("<script src='halo-nat.js'><\/script>")    
document.write("<script src='halo-nums.js'><\/script>")    
document.write("<script src='halo-pacer.js'><\/script>")    
document.write("<script src='halo-text.js'><\/script>")    
/*  x  proxy */  
document.write("<script src='x-s.js'><\/script>")    
/*  renderers */  
document.write("<script src='render-canvas.js'><\/script>")    
document.write("<script src='render-renderer.js'><\/script>")    
document.write("<script src='render-SVG.js'><\/script>")    
document.write("<script src='render-webgl.js'><\/script>")    
