/* d3*/
document.write("<script src='d3.v5.js'><\/script>")
document.write("<script src='d3-require.js'><\/script>")
document.write("<script src='d3-octree.js'><\/script>")
document.write("<script src='d3-inertia.js'><\/script>")
document.write("<script src='d3-geo.js'><\/script>")
document.write("<script src='d3-geo-voronoi.js'><\/script>")
document.write("<script src='d3-geo-projection.js'><\/script>")
document.write("<script src='d3-geo-projection-clip-polyhedral.js'><\/script>")
document.write("<script src='d3-geo-polygon.js'><\/script>")
document.write("<script src='d3-force-surface.js'><\/script>")
document.write("<script src='d3-force-pod.js'><\/script>")
document.write("<script src='d3-force-magnetic.js'><\/script>")
document.write("<script src='d3-force-bounce.js'><\/script>")
document.write("<script src='d3-force-3d.js'><\/script>")
/* topojson*/
document.write("<script src='topojson.v3.js'><\/script>")
/* three*/
document.write("<script src='three.js'><\/script>")
document.write("<script src='three-trackballcontrols.js'><\/script>")
/* tfj*/
document.write("<script src='tfjs.js'><\/script>")

